[workspace]
members = [
    "course1",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.81"
clap = "4.5.3"
nalgebra = "0.32.4"
rayon = "1.9.0"
